### ISSUE TITLE
Enhancement - LEXAN BODY SHELL

### ISSUE THREAD

**Issue by johndpope** [Roger-random/Sawppy_Rover#1]
There are dae collada files here that maybe suitable - may need some reworking.
https://bitbucket.org/theconstructcore/curiosity_mars_rover/commits/all

**Comment by johndpope** [comment]
<img width="595" alt="53470337-6afd7d80-3ab5-11e9-9bf9-648397fcc2af" src="https://user-images.githubusercontent.com/289994/53997901-26976f00-4192-11e9-9b0f-dda740c09bc6.png">

**Comment by johndpope** [comment]
https://www.ebay.com.au/itm/1-10-RC-Car-Lexan-Clear-Body-Shell-200mm-Lexus-LFA-Will-Fit-Yokomo-TAMIYA-HPI-/121875609990

was imaging a cover like this - 
![s-l1600](https://user-images.githubusercontent.com/289994/53998613-7f680700-4194-11e9-84d7-0ccb832a5f6a.jpg)

**Comment by johndpope** [comment]
<img width="758" alt="screen shot 2019-03-08 at 10 01 20 pm" src="https://user-images.githubusercontent.com/289994/54025306-3a70be80-41ee-11e9-8db9-8ed4ecbd560a.png">

https://www.youtube.com/watch?v=CQc6gAWl4dY

**Comment by johndpope** [comment]
https://www.youtube.com/watch?v=QuOAk0pgsGY

**Comment by johndpope** [comment]
https://www.lego.com/en-us/service/buildinginstructions/search?initialsearch=42081#?text=42081
came across this volvo concept - looks mint


<img width="1001" alt="Screen Shot 2019-03-10 at 9 33 43 AM" src="https://user-images.githubusercontent.com/289994/54085749-a8fd6b80-4317-11e9-968d-91d89db8828f.png">

![14d9d74c-5090-4c62-87fa-cb12293d4a2d_5e552383-eee0-44ca-8be0-a90000c15fdb_en-us_3_coverimage](https://user-images.githubusercontent.com/289994/54085760-d518ec80-4317-11e9-9c2d-8bd43ee147ae.jpg)

**Comment by johndpope** [comment]
<img width="982" alt="Screen Shot 2019-03-10 at 9 36 58 AM" src="https://user-images.githubusercontent.com/289994/54085788-1a3d1e80-4318-11e9-9dd6-77aa9a009dd6.png">
![Uploading Screen Shot 2019-03-10 at 9.36.48 AM.png…]()
![Uploading Screen Shot 2019-03-10 at 9.36.39 AM.png…]()

**Comment by Roger-random** [comment]
A Lexan shell would be a good optional component for Sawppy builders who want to make their rovers resemble Curiosity not just in mechanical geometry but also in cosmetic appearance. At the moment my focus is not on the rover's looks, but if anyone else wants to make these cosmetic shells happen that would be fantastic!

**Comment by Playville** [comment]
Hi Roger!
I just finished the mechanical build a few minutes ago and started planning on some “cosmetics”, especially on the body. As soon as I’m done id love to share the inventor-Files if you like to?

**Comment by johndpope** [comment]
Hi @playville - there are some png images inside the official 3D project (first link at top) that I guess could be used as decals. 

Feel free to post screen shots of work in progress. Would love to see. When your happy you can submit a pull request to merge your updates into project. Welcome  to the world of open source.

**Comment by johndpope** [comment]
https://bitbucket.org/theconstructcore/curiosity_mars_rover/src/94974385f14a1f229bf436f91552ab6384fd89b4/curiosity_mars_rover_description/meshes/tex_01.png?at=master&fileviewer=file-view-default

![tex_01](https://user-images.githubusercontent.com/289994/54097335-029c7f00-4386-11e9-8638-11b16b546001.png)

**Comment by johndpope** [comment]
Found this - 

<img width="627" alt="Screen Shot 2019-03-16 at 22 37 20" src="https://user-images.githubusercontent.com/289994/54474698-18a1b800-483c-11e9-9a27-092264d415b0.png">

https://www.thingiverse.com/thing:3493597


<img width="921" alt="Screen Shot 2019-03-16 at 22 38 58" src="https://user-images.githubusercontent.com/289994/54474710-4f77ce00-483c-11e9-9c9a-225626eb13ad.png">

https://www.thingiverse.com/thing:1606181

<img width="921" alt="Screen Shot 2019-03-16 at 22 39 25" src="https://user-images.githubusercontent.com/289994/54474730-7930f500-483c-11e9-95b6-92d8b555a242.png">

**Comment by Roger-random** [comment]
I'm happy to share that one of the Sawppy builders has made great progress at building cosmetic add-ons to make Sawppy look like Curiosity Rover. Please see [Laura McKeegan's project CJ ("Curiosity, Jr.") rover on hackaday.io](https://hackaday.io/project/165094).

![CJ Rover](https://cdn.hackaday.io/images/1777181561585042391.jpg)

And for anyone else who wishes to undertake a similar project, I've shared all the [3D resources I've found for Curiosity rover](https://newscrewdriver.com/2019/06/25/curiosity-rover-3d-resources/). The best one seems to be the Blender model released by NASA JPL.

![Curiosity 3D model](https://newscrewdriver.files.wordpress.com/2019/06/curiosity_static.glb-displayed-in-win10-3d-viewer.jpg)

**Comment by johndpope** [comment]
![00000-2855756243](https://github.com/Roger-random/Sawppy_Rover/assets/289994/f270d8c4-5e7d-4746-91e6-676affd99148)
![00001-630438866](https://github.com/Roger-random/Sawppy_Rover/assets/289994/062476fc-fe12-474c-bf3f-ca6c7d9d2e7a)
![00002-630438867](https://github.com/Roger-random/Sawppy_Rover/assets/289994/92f1487b-b425-4256-a86d-c098c27e7732)
![00003-630438868](https://github.com/Roger-random/Sawppy_Rover/assets/289994/6209cf4c-4f4c-4541-ad8
![00005-630438870](https://github.com/Roger-random/Sawppy_Rover/assets/289994/7a06767f-eafc-4350-a418-518ad7b0e284)
![00006-630438871](https://github.com/Roger-random/Sawppy_Rover/assets/289994/66825a74-397f-4246-adf3-39462f1da739)
![00007-630438872](https://github.com/Roger-random/Sawppy_Rover/assets/289994/a6c9e425-588f-4798-b4ed-c2c15679c25d)
![00008-630438873](https://github.com/Roger-random/Sawppy_Rover/assets/289994/cb8c1389-caa4-4e31-adf1-a3b9f2290bdc)
![00009-2492057210](https://github.com/Roger-random/Sawppy_Rover/assets/289994/2394fa0e-6611-4219-bbe3-0aba7d30b922)
![00010-2492057211](https://github.com/Roger-random/Sawppy_Rover/assets/289994/bdfb779a-8675-4466-96e5-af5c3cf90140)
6-9f1c03370418)
![00004-630438869](https://github.com/Roger-random/Sawppy_Rover/assets/289994/074ed15b-c852-4528-8372-0d2cde2cce38)

hi @Roger-random  - you might be interested to play around with stable diffusion
![00013-2492057214](https://github.com/Roger-random/Sawppy_Rover/assets/289994/7287992d-317d-4dec-a117-173bb80c3d09)
![00014-2492057215](https://github.com/Roger-random/Sawppy_Rover/assets/289994/bae44f53-d9fc-4276-9b21-ee7a30799450)
![00015-2492057216](https://github.com/Roger-random/Sawppy_Rover/assets/289994/3212615f-f188-4a36-bf74-58b527314d85)
![00016-2492057217](https://github.com/Roger-random/Sawppy_Rover/assets/289994/385f61d3-0105-457d-bcba-f15216be641f)
![00017-1606293674](https://github.com/Roger-random/Sawppy_Rover/assets/289994/672ac0b2-264b-4955-a293-772ea5c6ff7d)
![00018-1606293675](https://github.com/Roger-random/Sawppy_Rover/assets/289994/43f94b62-3336-46fc-b08c-eb870d632f68)
![00019-1606293676](https://github.com/Roger-random/Sawppy_Rover/assets/289994/366b5d35-02fa-4193-8c86-9f67ceebb81a)
![00020-1606293677](https://github.com/Roger-random/Sawppy_Rover/assets/289994/0b250b6d-6961-4fb1-9879-d1fc941507f4)
![00021-1606293678](https://github.com/Roger-random/Sawppy_Rover/assets/289994/b3208982-a3b4-4688-9014-81c11cf18adb)
![00022-1606293679](https://github.com/Roger-random/Sawppy_Rover/assets/289994/ee32766b-8e35-4371-a8fb-f8f86aaf2ab0)
![00023-1606293680](https://github.com/Roger-random/Sawppy_Rover/assets/289994/ee848da8-a0b0-4159-982b-f0828d3b60ff)
![00024-1606293681](https://github.com/Roger-random/Sawppy_Rover/assets/289994/456d3cd3-b84b-439b-8543-b9181fc77c88)
![00025-214048276](https://github.com/Roger-random/Sawppy_Rover/assets/289994/fce56c7d-91e2-4d17-a444-5856cb4377a3)
![00026-214048277](https://github.com/Roger-random/Sawppy_Rover/assets/289994/4f28a984-f700-42a6-9756-dc185cd9d157)
![00027-214048278](https://github.com/Roger-random/Sawppy_Rover/assets/289994/e4030ffd-8ce7-4815-8dc8-b1d595f7ff8c)
![00028-214048279](https://github.com/Roger-random/Sawppy_Rover/assets/289994/dda7bd3d-b1e7-4f95-b22f-825951ebc263)
![00029-214048280](https://github.com/Roger-random/Sawppy_Rover/assets/289994/fdf94703-dcc4-4d64-bc20-fbd2fa7a49cc)
![00030-214048281](https://github.com/Roger-random/Sawppy_Rover/assets/289994/fab1cf2d-4700-416c-a015-503853237c13)
![00031-214048282](https://github.com/Roger-random/Sawppy_Rover/assets/289994/e24c1db5-c069-424d-b434-d29b0ebeeacc)
![00032-214048283](https://github.com/Roger-random/Sawppy_Rover/assets/289994/7d82bc0d-40a6-4902-a3cb-8936c8839a25)
![00033-4048579585](https://github.com/Roger-random/Sawppy_Rover/assets/289994/1f49d8ed-0c47-49c7-952d-47edb31a700c)
![00034-4048579586](https://github.com/Roger-random/Sawppy_Rover/assets/289994/e9d282ee-0882-49c4-9fb9-574df281bc4a)
![00035-4048579587](https://github.com/Roger-random/Sawppy_Rover/assets/289994/ee420a44-da1a-400c-9feb-2b13fd289184)
![00036-4048579588](https://github.com/Roger-random/Sawppy_Rover/assets/289994/d0d4bc0e-e205-4ee9-8d1d-6e6e653eb458)
![00037-4048579589](https://github.com/Roger-random/Sawppy_Rover/assets/289994/fd6b5d65-ee75-470b-85d1-570cde6a3736)
![00038-4048579590](https://github.com/Roger-random/Sawppy_Rover/assets/289994/155d3c78-1130-4770-b8f9-3d0a545693de)
![00039-4048579591](https://github.com/Roger-random/Sawppy_Rover/assets/289994/525c4257-204a-4bd8-aa2d-ef85aedd0189)
![00040-4048579592](https://github.com/Roger-random/Sawppy_Rover/assets/289994/c6a12086-9b1c-4620-b4b0-1686de5596bc)
![00041-642516926](https://github.com/Roger-random/Sawppy_Rover/assets/289994/50c01e99-7e39-4c7c-9edc-8b2ae708b96b)
![00042-642516927](https://github.com/Roger-random/Sawppy_Rover/assets/289994/7b53ac8c-e38b-45ed-b699-b8c949a15964)
![00043-642516928](https://github.com/Roger-random/Sawppy_Rover/assets/289994/393bc24b-ceb7-4ec6-974a-811ff363e086)
![00044-642516929](https://github.com/Roger-random/Sawppy_Rover/assets/289994/e22667e5-a962-4fa9-9b79-d53974da8110)
![00045-642516930](https://github.com/Roger-random/Sawppy_Rover/assets/289994/2653a50d-a95a-4b8c-8273-2f8b504e0297)
![00046-642516931](https://github.com/Roger-random/Sawppy_Rover/assets/289994/edb8c43b-ce02-4ab3-b16c-96a566e7c9fb)
![00047-642516932](https://github.com/Roger-random/Sawppy_Rover/assets/289994/cc375d57-d094-4601-b957-7046a2b15035)
![00048-642516933](https://github.com/Roger-random/Sawppy_Rover/assets/289994/21acab82-0cf4-4034-84d3-3a9962562ace)
![00049-2905501749](https://github.com/Roger-random/Sawppy_Rover/assets/289994/ceda026d-a4f6-4a6a-902c-e8e911b0651b)
![00050-2905501750](https://github.com/Roger-random/Sawppy_Rover/assets/289994/6d98e35b-748d-42b2-a66e-44c6fdf193e0)
![00051-2905501751](https://github.com/Roger-random/Sawppy_Rover/assets/289994/a21f16ac-0ce2-4d9a-b4a6-db557d5b18b0)
![00052-2905501752](https://github.com/Roger-random/Sawppy_Rover/assets/289994/b4c85961-d1de-4242-973c-041e2568a482)
![00053-2905501753](https://github.com/Roger-random/Sawppy_Rover/assets/289994/7ce66996-e45d-424e-be22-35b7bb83237e)
![00054-2905501754](https://github.com/Roger-random/Sawppy_Rover/assets/289994/c7d0dac8-2bb9-4e57-9bad-39e76a3fb49f)
![00055-2905501755](https://github.com/Roger-random/Sawppy_Rover/assets/289994/2a863754-7bda-4183-8f04-668f9b962689)
![00056-2905501756](https://github.com/Roger-random/Sawppy_Rover/assets/289994/f8b56d35-5790-4317-b68f-728c450196f2)

Here I just prompt
 "mars curiosity rover lexan body shell, technical drawing, pencil![Uploading 00
![00012-2492057213](https://github.com/Roger-random/Sawppy_Rover/assets/289994/c662cdbe-1547-4edc-abb6-74f8c8bf4ec3)
011-2492057212.png…]()



also not sure you saw this - 
https://www.youtube.com/watch?v=fY32WFY-LuM&ab_channel=RobotGarden
