### ISSUE TITLE
onShape CAD document

### ISSUE THREAD

**Issue by digitalsmeg** [Roger-random/Sawppy_Rover#8]
Is this intended to be behind a paywall?  I know models can be shared publicly but the Swappy document is forcing me to register with onShape just to view it. Unless I overlooked it, do you guys have a CAD file of the entire build somewhere in this repo?

**Comment by Roger-random** [comment]
There is no paywall but you do have to register with Onshape on their free tier for makers and hobbyists. https://www.onshape.com/products/free

**Comment by digitalsmeg** [comment]
I totally missed that. Thanks for the link!
